name: Store scraper

on:
  schedule:
    - cron: '6 0 * * *'
  workflow_dispatch:

jobs:
  scrape_rimi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Scrape Rimi
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          python scrape_rimi_lv.py
          python scrape_rimi_lt.py

  scrape_barbora:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Scrape Barbora
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          python scrape_barbora_lv.py
          python scrape_barbora_lt.py